pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Report'
    contents: 'dist/** '
    targetFolder: '/var/www/sites-available/newFronEnd/'
    cleanTargetFolder: true
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'Report'
    runOptions: 'commands'
    commands: 'sudo nginx -s reload'
    readyTimeout: '20000'