
// tslint:disable-next-line: variable-name
export const LottieJsons = {
  approved_checked: 'assets/lottie/lordicons/approved_checked.json',
  coin_dollar: 'assets/lottie/lordicons/coin_dollar.json',
  link: 'assets/lottie/lordicons/link.json',
  page_loader_2: 'assets/lottie/lordicons/page_loader_2.json',
  share: 'assets/lottie/lordicons/share.json',
  arrow_down: 'assets/lottie/lordicons/arrow_down.json',
  conversation_bubble: 'assets/lottie/lordicons/conversation_bubble.json',
  location_pin: 'assets/lottie/lordicons/location_pin.json',
  page_loader_3: 'assets/lottie/lordicons/page_loader_3.json',
  shopping_card_basket: 'assets/lottie/lordicons/shopping_card_basket.json',
  arrow_left: 'assets/lottie/lordicons/arrow_left.json',
  copy: 'assets/lottie/lordicons/copy.json',
  location_radar: 'assets/lottie/lordicons/location_radar.json',
  page_loader: 'assets/lottie/lordicons/page_loader.json',
  shopping_card_big_basket: 'assets/lottie/lordicons/shopping_card_big_basket.json',
  arrow_right: 'assets/lottie/lordicons/arrow_right.json',
  dowload: 'assets/lottie/lordicons/dowload.json',
  log_out: 'assets/lottie/lordicons/log_out.json',
  pen_pencil_edit: 'assets/lottie/lordicons/pen_pencil_edit.json',
  star: 'assets/lottie/lordicons/star.json',
  arrow_up: 'assets/lottie/lordicons/arrow_up.json',
  gear_rotation_settings: 'assets/lottie/lordicons/gear_rotation_settings.json',
  man_avatar: 'assets/lottie/lordicons/man_avatar.json',
  play_hover: 'assets/lottie/lordicons/play_hover.json',
  tag: 'assets/lottie/lordicons/tag.json',
  bar_chart: 'assets/lottie/lordicons/bar_chart.json',
  hamburger: 'assets/lottie/lordicons/hamburger.json',
  minus_button: 'assets/lottie/lordicons/minus_button.json',
  plus_button: 'assets/lottie/lordicons/plus_button.json',
  trash_bin: 'assets/lottie/lordicons/trash_bin.json',
  bulb_shake: 'assets/lottie/lordicons/bulb_shake.json',
  head_phones: 'assets/lottie/lordicons/head_phones.json',
  mobile_phone: 'assets/lottie/lordicons/mobile_phone.json',
  radio_button: 'assets/lottie/lordicons/radio_button.json',
  upload: 'assets/lottie/lordicons/upload.json',
  chart_pie: 'assets/lottie/lordicons/chart_pie.json',
  heart_love: 'assets/lottie/lordicons/heart_love.json',
  music_note: 'assets/lottie/lordicons/music_note.json',
  search_magnifier: 'assets/lottie/lordicons/search_magnifier.json',
  wifi: 'assets/lottie/lordicons/wifi.json',
  check_box: 'assets/lottie/lordicons/check_box.json',
  home: 'assets/lottie/lordicons/home.json',
  padlock_locked: 'assets/lottie/lordicons/padlock_locked.json',
  settings: 'assets/lottie/lordicons/settings.json',
  woman_avatar: 'assets/lottie/lordicons/woman_avatar.json',
  close: 'assets/lottie/lordicons/close.json',
  like_hand: 'assets/lottie/lordicons/like_hand.json',
  padlock_unlocked: 'assets/lottie/lordicons/padlock_unlocked.json',
  share_dots: 'assets/lottie/lordicons/share_dots.json',
  world_spinning: 'assets/lottie/lordicons/world_spinning.json',
  car: 'assets/lottie/lordicons/car.json'
};

export type LottieJson = keyof typeof LottieJsons;
